@BASE_URL = {{$dotenv BASE_URL}}
@USERNAME = {{$dotenv USERNAME}}
@PASSWORD = {{$dotenv PASSWORD}}
@EMAIL = {{$dotenv EMAIL}}

### Create a new user
POST {{BASE_URL}}/api/users
Content-Type: application/json

{
    "username": "{{USERNAME}}",
    "password": "{{PASSWORD}}",
    "email": "{{EMAIL}}"
}